name: Report a bug
description: Describe a bug or a problem you may have identified.
title: "[Bug] "
labels: ["bug"]
assignees:
  - hazzuk

body:
  - type: markdown
    attributes:
      value: "Thank you for reporting a bug. Please fill out the sections below:"

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help the maintainers work faster.
      options:
        - label: I have searched for duplicate or closed issues
          required: true

  - type: input
    id: version
    attributes:
      label: What version are you using?
      description: Specify the version of the software where the bug occurs.
      placeholder: "e.g. 1.0.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: Explain what's happening, steps to reproduce it and any screenshots.
      placeholder: "Provide a step by step description of the bug."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: "What should normally happen?"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened.
      placeholder: "What happened instead?"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system(s) are you seeing the issue on?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Any additional notes
      description: Highlight important context, possible solutions or any extra details.
      placeholder: "Include context and observations."
    validations:
      required: false